const a = [
    {
        id: 11344,
        position: 101,
        positionTitle: '软件开发-后台开发方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CDG CSIG IEG PCG TEG WXG S2 S3 ',
        workCities: '深圳总部 北京 天津 上海 成都 杭州 广州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11345,
        position: 102,
        positionTitle: '软件开发-PC客户端开发方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CSIG IEG PCG WXG ',
        workCities: '深圳总部 上海 北京 广州 成都 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11346,
        position: 103,
        positionTitle: '软件开发-移动客户端开发方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CDG CSIG IEG PCG WXG ',
        workCities: '深圳总部 北京 成都 广州 上海 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11347,
        position: 104,
        positionTitle: '软件开发-测试开发方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CDG CSIG IEG TEG WXG ',
        workCities: '深圳总部 上海 广州 北京 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11348,
        position: 105,
        positionTitle: '软件开发-运营开发方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CDG CSIG IEG TEG WXG ',
        workCities: '深圳总部 上海 北京 广州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11349,
        position: 106,
        positionTitle: '软件开发-前端开发方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CDG CSIG IEG PCG TEG WXG ',
        workCities: '深圳总部 北京 成都 上海 广州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11350,
        position: 107,
        positionTitle: '软件开发-游戏客户端开发方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'IEG PCG ',
        workCities: '深圳总部 上海 成都 杭州 中国香港 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11351,
        position: 109,
        positionTitle: '视觉设计',
        positionFamily: 4,
        projectId: 1,
        bgs: 'CDG CSIG IEG PCG ',
        workCities: '北京 深圳总部 上海 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11352,
        position: 111,
        positionTitle: 'UI开发',
        positionFamily: 4,
        projectId: 1,
        bgs: 'PCG ',
        workCities: '深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11353,
        position: 112,
        positionTitle: '安全技术',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CDG CSIG IEG PCG TEG WXG ',
        workCities: '深圳总部 上海 北京 广州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11354,
        position: 114,
        positionTitle: '测试与质量管理',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CSIG IEG WXG ',
        workCities: '深圳总部 成都 上海 北京 广州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11355,
        position: 115,
        positionTitle: '游戏策划培训生',
        positionFamily: 3,
        projectId: 1,
        bgs: 'IEG ',
        workCities: '深圳总部 上海 成都 杭州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11356,
        position: 117,
        positionTitle: '营销',
        positionFamily: 5,
        projectId: 1,
        bgs: 'CDG CSIG IEG PCG ',
        workCities: '北京 深圳总部 上海 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11357,
        position: 118,
        positionTitle: '内容运营',
        positionFamily: 3,
        projectId: 1,
        bgs: 'PCG TEG ',
        workCities: '北京 深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11358,
        position: 120,
        positionTitle: '多媒体设计',
        positionFamily: 4,
        projectId: 1,
        bgs: 'PCG ',
        workCities: '深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11359,
        position: 121,
        positionTitle: '行政专员',
        positionFamily: 5,
        projectId: 1,
        bgs: 'S1 ',
        workCities: '深圳总部 北京 上海 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11360,
        position: 122,
        positionTitle: '财经线培训生-专业类',
        positionFamily: 5,
        projectId: 1,
        bgs: 'S2 ',
        workCities: '深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11361,
        position: 124,
        positionTitle: '商业分析',
        positionFamily: 5,
        projectId: 1,
        bgs: 'CDG CSIG IEG PCG ',
        workCities: '北京 深圳总部 广州 上海 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11362,
        position: 125,
        positionTitle: '产品策划/运营',
        positionFamily: 3,
        projectId: 1,
        bgs: 'CDG CSIG IEG PCG TEG S1 S3 ',
        workCities: '深圳总部 北京 上海 成都 广州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11363,
        position: 135,
        positionTitle: '市场研究',
        positionFamily: 5,
        projectId: 1,
        bgs: 'IEG ',
        workCities: '深圳总部 上海 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11364,
        position: 137,
        positionTitle: '软件开发-全栈开发方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CDG CSIG IEG PCG TEG WXG ',
        workCities: '深圳总部 上海 北京 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11365,
        position: 138,
        positionTitle: '公关',
        positionFamily: 5,
        projectId: 1,
        bgs: 'CDG ',
        workCities: '北京 上海 深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11366,
        position: 139,
        positionTitle: '用户研究',
        positionFamily: 4,
        projectId: 1,
        bgs: 'PCG ',
        workCities: '深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11367,
        position: 140,
        positionTitle: '交互设计',
        positionFamily: 4,
        projectId: 1,
        bgs: 'CDG CSIG IEG PCG ',
        workCities: '深圳总部 北京 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11368,
        position: 141,
        positionTitle: '游戏发行/运营培训生',
        positionFamily: 3,
        projectId: 1,
        bgs: 'IEG PCG ',
        workCities: '深圳总部 北京 成都 上海 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11369,
        position: 142,
        positionTitle: '秘书',
        positionFamily: 5,
        projectId: 1,
        bgs: 'CDG CSIG IEG TEG S1 ',
        workCities: '深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11370,
        position: 144,
        positionTitle: '技术运营',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CDG CSIG IEG TEG WXG ',
        workCities: '深圳总部 上海 北京 成都 广州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11371,
        position: 146,
        positionTitle: '法务',
        positionFamily: 5,
        projectId: 1,
        bgs: 'S1 ',
        workCities: '深圳总部 北京 中国香港 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11372,
        position: 159,
        positionTitle: '采购商务管理',
        positionFamily: 5,
        projectId: 1,
        bgs: 'PCG S1 ',
        workCities: '深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11373,
        position: 161,
        positionTitle: '平台型产品经理（技术背景）',
        positionFamily: 3,
        projectId: 1,
        bgs: 'CDG CSIG IEG ',
        workCities: '深圳总部 北京 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11374,
        position: 172,
        positionTitle: '投资分析',
        positionFamily: 5,
        projectId: 1,
        bgs: 'CDG ',
        workCities: '北京 上海 深圳总部 中国香港 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11375,
        position: 176,
        positionTitle: '技术研究-机器学习方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CDG CSIG IEG PCG TEG WXG S1 ',
        workCities: '北京 深圳总部 合肥 成都 广州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11376,
        position: 177,
        positionTitle: '技术研究-计算机视觉方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CSIG IEG PCG TEG WXG ',
        workCities: '深圳总部 北京 上海 合肥 广州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11377,
        position: 178,
        positionTitle: '技术研究-多媒体处理方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CSIG IEG PCG TEG WXG ',
        workCities: '深圳总部 上海 北京 广州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11378,
        position: 179,
        positionTitle: '技术研究-自然语言处理方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CDG CSIG IEG PCG TEG WXG ',
        workCities: '北京 深圳总部 成都 上海 广州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11379,
        position: 180,
        positionTitle: '技术研究-其他方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CDG CSIG TEG ',
        workCities: '深圳总部 北京 上海 中国香港 杭州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11380,
        position: 184,
        positionTitle: '公共事务',
        positionFamily: 5,
        projectId: 1,
        bgs: 'S1 S3 ',
        workCities: '成都 深圳总部 重庆 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11381,
        position: 190,
        positionTitle: '制片人助理',
        positionFamily: 3,
        projectId: 1,
        bgs: 'PCG ',
        workCities: '北京 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11382,
        position: 191,
        positionTitle: '软件开发-数据工程',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CDG CSIG IEG PCG TEG S1 S2 ',
        workCities: '深圳总部 北京 上海 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11383,
        position: 194,
        positionTitle: '软件开发-云计算开发方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CSIG ',
        workCities: '成都 深圳总部 北京 上海 杭州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11384,
        position: 196,
        positionTitle: '云计算产品经理',
        positionFamily: 3,
        projectId: 1,
        bgs: 'CSIG ',
        workCities: '深圳总部 北京 上海 杭州 成都 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11385,
        position: 198,
        positionTitle: '内容创作',
        positionFamily: 3,
        projectId: 1,
        bgs: 'IEG PCG ',
        workCities: '北京 成都 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11386,
        position: 200,
        positionTitle: '投资运营分析师',
        positionFamily: 5,
        projectId: 1,
        bgs: 'CDG ',
        workCities: '北京 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11387,
        position: 208,
        positionTitle: '技术美术',
        positionFamily: 4,
        projectId: 1,
        bgs: 'IEG PCG ',
        workCities: '深圳总部 上海 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11388,
        position: 210,
        positionTitle: '商务拓展',
        positionFamily: 5,
        projectId: 1,
        bgs: 'CSIG IEG PCG ',
        workCities: '北京 深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11389,
        position: 211,
        positionTitle: '安全策略',
        positionFamily: 5,
        projectId: 1,
        bgs: 'S1 ',
        workCities: '深圳总部 广州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11390,
        position: 218,
        positionTitle: '专利',
        positionFamily: 5,
        projectId: 1,
        bgs: 'S1 ',
        workCities: '深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11391,
        position: 220,
        positionTitle: '金融合规',
        positionFamily: 3,
        projectId: 1,
        bgs: 'S1 ',
        workCities: '深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11392,
        position: 221,
        positionTitle: '软件开发-游戏引擎开发方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'IEG PCG ',
        workCities: '深圳总部 上海 杭州 成都 北京 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11393,
        position: 222,
        positionTitle: '财经线培训生-分析类',
        positionFamily: 5,
        projectId: 1,
        bgs: 'S2 ',
        workCities: '深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11394,
        position: 223,
        positionTitle: '公共政策-产业、金融和数据治理研究方向',
        positionFamily: 5,
        projectId: 1,
        bgs: 'S1 ',
        workCities: '深圳总部 北京 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11395,
        position: 225,
        positionTitle: '产品体验设计',
        positionFamily: 4,
        projectId: 1,
        bgs: 'CSIG IEG PCG ',
        workCities: '深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11396,
        position: 232,
        positionTitle: '解决方案-行业咨询方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CSIG ',
        workCities: '上海 深圳总部 北京 成都 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11397,
        position: 233,
        positionTitle: '解决方案-技术咨询方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CSIG ',
        workCities: '广州 上海 北京 深圳总部 武汉 长沙 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11398,
        position: 236,
        positionTitle: '技术研究-计算机图形学方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'IEG PCG TEG ',
        workCities: '深圳总部 上海 成都 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11399,
        position: 237,
        positionTitle: '技术研究-机器人方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'TEG ',
        workCities: '深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11400,
        position: 238,
        positionTitle: '技术研究-数据科学方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CDG CSIG IEG PCG WXG S1 ',
        workCities: '北京 深圳总部 成都 上海 广州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11401,
        position: 243,
        positionTitle: '2D角色设计',
        positionFamily: 4,
        projectId: 1,
        bgs: 'IEG PCG ',
        workCities: '深圳总部 成都 上海 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11402,
        position: 244,
        positionTitle: '2D场景设计',
        positionFamily: 4,
        projectId: 1,
        bgs: 'IEG PCG ',
        workCities: '深圳总部 成都 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11403,
        position: 245,
        positionTitle: '3D角色设计',
        positionFamily: 4,
        projectId: 1,
        bgs: 'IEG ',
        workCities: '深圳总部 上海 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11404,
        position: 246,
        positionTitle: '3D场景设计',
        positionFamily: 4,
        projectId: 1,
        bgs: 'IEG ',
        workCities: '深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11405,
        position: 247,
        positionTitle: '动画',
        positionFamily: 4,
        projectId: 1,
        bgs: 'IEG ',
        workCities: '深圳总部 成都 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11406,
        position: 248,
        positionTitle: '特效',
        positionFamily: 4,
        projectId: 1,
        bgs: 'IEG ',
        workCities: '深圳总部 成都 上海 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11407,
        position: 252,
        positionTitle: '金融风险控制',
        positionFamily: 3,
        projectId: 1,
        bgs: 'CDG S1 ',
        workCities: '深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11408,
        position: 254,
        positionTitle: '项目管理',
        positionFamily: 3,
        projectId: 1,
        bgs: 'CDG CSIG IEG PCG S1 ',
        workCities: '北京 深圳总部 成都 上海 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11409,
        position: 255,
        positionTitle: '硬件开发-芯片设计方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'CSIG TEG ',
        workCities: '上海 深圳总部 杭州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11410,
        position: 256,
        positionTitle: '硬件开发-芯片验证方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'TEG ',
        workCities: '深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11411,
        position: 257,
        positionTitle: '技术研究-多模态方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'IEG PCG TEG WXG ',
        workCities: '北京 深圳总部 上海 广州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11412,
        position: 259,
        positionTitle: '音频策划',
        positionFamily: 3,
        projectId: 1,
        bgs: 'IEG ',
        workCities: '深圳总部 上海 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11413,
        position: 260,
        positionTitle: '人力资源培训生',
        positionFamily: 5,
        projectId: 1,
        bgs: 'S3 ',
        workCities: '深圳总部 广州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11414,
        position: 261,
        positionTitle: '行政(商业项目管理)',
        positionFamily: 5,
        projectId: 1,
        bgs: 'S1 ',
        workCities: '深圳总部 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 11415,
        position: 262,
        positionTitle: '技术研究-推荐算法方向',
        positionFamily: 2,
        projectId: 1,
        bgs: 'PCG WXG ',
        workCities: '北京 深圳总部 广州 ',
        positionUrl: null,
        positionSource: 'oa',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 1765520279498399700,
        position: 1765520279498399700,
        positionTitle: 'TiMi Montreal- Junior Character Concept Artist 102796',
        positionFamily: null,
        projectId: 1,
        bgs: 'IEG ',
        workCities: 'Canada-Montreal',
        positionUrl:
            'https://tencent.wd1.myworkdayjobs.com/Tencent_Careers/job/Canada-Montreal/TiMi-Montreal--Junior-Character-Concept-Artist_R102796-1',
        positionSource: 'workday',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 1765520275186655200,
        position: 1765520275186655200,
        positionTitle: 'TiMi Montreal – Junior Tools Programmer 102800',
        positionFamily: null,
        projectId: 1,
        bgs: 'IEG ',
        workCities: 'Canada-Montreal',
        positionUrl:
            'https://tencent.wd1.myworkdayjobs.com/Tencent_Careers/job/Canada-Montreal/TiMi-Montreal---Junior-Tools-Programmer_R102800-2',
        positionSource: 'workday',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 1692315406045290500,
        position: 1692315406045290500,
        positionTitle: 'Operations & Development Engineer 101736',
        positionFamily: null,
        projectId: 1,
        bgs: 'IEG ',
        workCities: 'Singapore-CapitalSpring',
        positionUrl:
            'https://tencent.wd1.myworkdayjobs.com/Tencent_Careers/job/Singapore-CapitalSpring/Operations---Development-Engineer_R101736',
        positionSource: 'workday',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 1760220377218293800,
        position: 1760220377218293800,
        positionTitle: 'Tencent Cloud Associate Account Representative 102020',
        positionFamily: null,
        projectId: 1,
        bgs: 'CSIG ',
        workCities: 'Japan-Tokyo-Toranomon',
        positionUrl:
            'https://tencent.wd1.myworkdayjobs.com/Tencent_Careers/job/Japan-Tokyo-Toranomon/--2023-24-_R102020-1',
        positionSource: 'workday',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 1760643113279299600,
        position: 1760643113279299600,
        positionTitle:
            'Tencent Cloud Associate Account Representative (Sales Trainee) 102746',
        positionFamily: null,
        projectId: 1,
        bgs: 'CSIG ',
        workCities: 'S.Korea-Seoul-Gangnam Finance Center',
        positionUrl:
            'https://tencent.wd1.myworkdayjobs.com/Tencent_Careers/job/SKorea-Seoul-Gangnam-Finance-Center/Tencent-Cloud-Associate-Account-Representative--Sales-Trainee-_R102746',
        positionSource: 'workday',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 1752791437251977200,
        position: 1752791437251977200,
        positionTitle: 'Site Reliability Engineer 101830',
        positionFamily: null,
        projectId: 1,
        bgs: 'IEG ',
        workCities: 'US-Los Angeles',
        positionUrl:
            'https://tencent.wd1.myworkdayjobs.com/Tencent_Careers/job/US-Los-Angeles/Site-Reliability-Engineer_R101830-1',
        positionSource: 'workday',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 1692315392497688600,
        position: 1692315392497688600,
        positionTitle: 'AI Applications Analyst 101731',
        positionFamily: null,
        projectId: 1,
        bgs: 'Overseas Functional System ',
        workCities: 'US-Palo Alto',
        positionUrl:
            'https://tencent.wd1.myworkdayjobs.com/Tencent_Careers/job/US-Palo-Alto/AI-Applications-Analyst_R101731',
        positionSource: 'workday',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 1700001068777218000,
        position: 1700001068777218000,
        positionTitle: 'Senior Researcher 101857',
        positionFamily: null,
        projectId: 1,
        bgs: 'IEG ',
        workCities: 'Australia-Canberra',
        positionUrl:
            'https://tencent.wd1.myworkdayjobs.com/Tencent_Careers/job/Australia-Canberra/Senior-Researcher_R101857',
        positionSource: 'workday',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 1700001071629344800,
        position: 1700001071629344800,
        positionTitle: 'Associate Legal Counsel 101796',
        positionFamily: null,
        projectId: 1,
        bgs: 'S1 ',
        workCities: 'Singapore-WeWork',
        positionUrl:
            'https://tencent.wd1.myworkdayjobs.com/Tencent_Careers/job/Singapore-WeWork/Legal-Assistant_R101796-1',
        positionSource: 'workday',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 1731558966489522200,
        position: 1731558966489522200,
        positionTitle: 'Data Scientist Associate 102388',
        positionFamily: null,
        projectId: 1,
        bgs: 'IEG ',
        workCities: 'US-Palo Alto',
        positionUrl:
            'https://tencent.wd1.myworkdayjobs.com/Tencent_Careers/job/US-Palo-Alto/Data-Scientist-Associate_R102388-1',
        positionSource: 'workday',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 1719373673753747500,
        position: 1719373673753747500,
        positionTitle: 'TiMi Montreal- Junior Gameplay Animator 102057',
        positionFamily: null,
        projectId: 1,
        bgs: 'IEG ',
        workCities: 'Montreal',
        positionUrl:
            'https://tencent.wd1.myworkdayjobs.com/Tencent_Careers/job/Canada-Montreal/TiMi-Montreal--Junior-Gameplay-Animator_R102057-2',
        positionSource: 'workday',
        projectName: '应届生',
        recruitLabelName: '应届生'
    },
    {
        id: 1692315398029975600,
        position: 1692315398029975600,
        positionTitle: 'DevOps Engineer 101733',
        positionFamily: null,
        projectId: 1,
        bgs: 'TEG ',
        workCities: 'Palo Alto',
        positionUrl:
            'https://tencent.wd1.myworkdayjobs.com/Tencent_Careers/job/US-Palo-Alto/DevOps-Engineer_R101733',
        positionSource: 'workday',
        projectName: '应届生',
        recruitLabelName: '应届生'
    }
];

console.log(a.map((i) => i.position));
